-- Requests from users who want to advertise on Parking SV.

create table if not exists public.advertising_requests (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  business_name text not null,
  business_category text not null,
  campaign_goal text not null,
  description text not null,
  budget_range text,
  preferred_contact text not null,
  website_or_social text,
  contact_name text not null,
  contact_email text not null,
  contact_phone text,
  terms_accepted boolean not null default false,
  status text not null default 'pendiente',
  response_due_at timestamptz not null default (now() + interval '7 days'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.advertising_requests enable row level security;

drop policy if exists "Users can read own advertising requests" on public.advertising_requests;
create policy "Users can read own advertising requests"
on public.advertising_requests
for select
using (
  exists (
    select 1
    from public.users u
    where u.id = user_id
      and lower(u.email) = public.current_auth_email()
  )
);

drop policy if exists "Users can create own advertising requests" on public.advertising_requests;
create policy "Users can create own advertising requests"
on public.advertising_requests
for insert
with check (
  exists (
    select 1
    from public.users u
    where u.id = user_id
      and lower(u.email) = public.current_auth_email()
  )
);

drop policy if exists "Users can update own advertising requests" on public.advertising_requests;
create policy "Users can update own advertising requests"
on public.advertising_requests
for update
using (
  exists (
    select 1
    from public.users u
    where u.id = user_id
      and lower(u.email) = public.current_auth_email()
  )
)
with check (
  exists (
    select 1
    from public.users u
    where u.id = user_id
      and lower(u.email) = public.current_auth_email()
  )
);
